Create a NumPy array


In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
arr = np.array(42)

print(arr)

42


create a 1-D array

In [4]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


# create a 2- D array

In [5]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


# create a 3-D array

In [6]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


# create a high dimensional array

In [7]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


# check dimension of the arrays

In [8]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


# array indexing

In [9]:
arr = np.array([1, 2, 3, 4])

print(arr[0])

1


In [10]:
print(arr[2] + arr[3])

7


In [11]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  2


In [12]:
print('5th element on 2nd row: ', arr[1, 4])

5th element on 2nd row:  10


In [13]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

6


In [14]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


# array slicing

In [15]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [16]:
print(arr[4:])

[5 6 7]


In [17]:
print(arr[:4])

[1 2 3 4]


In [18]:
print(arr[-3:-1])

[5 6]


In [19]:
# steps
print(arr[1:5:2])

[2 4]


In [20]:
# every other element after 1
print(arr[::2])

[1 3 5 7]


In [21]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


In [22]:
print(arr[0:2, 2])

[3 8]


In [23]:
print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


# shape of the array

In [24]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [25]:
print(arr)
print('shape of array :', arr.shape)

[[1 2 3 4]
 [5 6 7 8]]
shape of array : (2, 4)


In [26]:
# reshaping the array

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [27]:
# reshaping from 1-D to 3-D

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


# iterating array

In [28]:
arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


In [29]:
# 2-D array
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [30]:
# iterate each scaler element

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


In [31]:
# iterate each scaler element from 3-D array

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


# searching in an array

In [32]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6], dtype=int64),)


In [33]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7], dtype=int64),)


In [34]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 1)

print(x)

(array([0, 2, 4, 6], dtype=int64),)


In [36]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 9)

print(x)

3
